# Generated by Django 2.2.10 on 2021-01-20 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=240, null=True)),
                ('type', models.CharField(blank=True, choices=[('text', 'text'), ('choose_one', 'choose one answer'), ('choose_many', 'choose one or more answers')], default='text', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TinyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=80, null=True)),
                ('date_start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_end', models.DateTimeField(blank=True)),
                ('description', models.CharField(default='', max_length=80, null=True)),
                ('questions', models.ManyToManyField(blank=True, to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.ForeignKey(blank=True, on_delete='cascade', to='polls.Poll')),
                ('user_id', models.ForeignKey(blank=True, on_delete='cascade', to='polls.TinyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=360, null=True)),
                ('question', models.ForeignKey(blank=True, on_delete='cascade', to='polls.Question')),
            ],
        ),
    ]
