# Generated by Django 2.2.10 on 2021-01-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='finished_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='polls.FinishedPoll'),
        ),
        migrations.AlterField(
            model_name='finishedpoll',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='TinyUser',
        ),
    ]
