# Generated by Django 2.2.10 on 2021-01-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210120_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedpoll',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
