# Generated by Django 2.2.10 on 2021-01-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210121_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='finished_poll',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.FinishedPoll'),
            preserve_default=False,
        ),
    ]
